import asyncio
import logging
from app.main import main

if __name__ == "__main__":
    # try:
    asyncio.run(main())
    # except Exception as e:
    #     logging.error(f"Ошибка при запуске бота: {e}")
